version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: connect-postgres
    environment:
      POSTGRES_USER: sahil
      POSTGRES_DB: newsconnect
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
